POST http://localhost:8080/api/register
Content-Type: application/json

{
    "name": "Osup",
    "email": "osup@example.com",
    "role": "admin",
    "password": "password123"
}

###

POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "osup@example.com",
    "password": "password123"
}


### GET request to route server
GET http://localhost:8080/api/dashboard/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdKaWxiaUBleGFtcGxlLmNvbSIsImV4cCI6MTc0ODM1MjM1Nywicm9sZXMiOlt7ImlkIjoyLCJuYW1lIjoidXNlciIsImNyZWF0ZWRfYXQiOiIyMDI1LTA1LTI2VDE4OjAzOjU4LjYyNSswNzowMCIsInVwZGF0ZWRfYXQiOiIyMDI1LTA1LTI2VDE4OjAzOjU4LjYyNSswNzowMCJ9XSwidXNlcl9pZCI6M30.5j6TwTGy70dCHqCS6qbMjus0ejgCmCDMGYj_1azCwHQ

###