POST http://localhost:8080/api/dashboard/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ4MzYyMzcyLCJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJhZG1pbiIsImNyZWF0ZWRfYXQiOiIyMDI1LTA1LTI2VDIxOjE1OjU5LjM3OSswNzowMCIsInVwZGF0ZWRfYXQiOiIyMDI1LTA1LTI2VDIxOjE1OjU5LjM3OSswNzowMCJ9XSwidXNlcl9pZCI6MX0.wPjlN5xw_f6uYvACDVg2RsyriqPTBAcxDlX26mnWQ0Y
Content-Type: application/json

{
  "title": "Berita Terbaru Hari Ini Juga",
  "body": "Isi lengkap artikel"
}

###
GET http://localhost:8080/api/dashboard/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ4MzYyMzcyLCJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJhZG1pbiIsImNyZWF0ZWRfYXQiOiIyMDI1LTA1LTI2VDIxOjE1OjU5LjM3OSswNzowMCIsInVwZGF0ZWRfYXQiOiIyMDI1LTA1LTI2VDIxOjE1OjU5LjM3OSswNzowMCJ9XSwidXNlcl9pZCI6MX0.wPjlN5xw_f6uYvACDVg2RsyriqPTBAcxDlX26mnWQ0Y

###
PUT http://localhost:8080/api/dashboard/post/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ4MzYyMzcyLCJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJhZG1pbiIsImNyZWF0ZWRfYXQiOiIyMDI1LTA1LTI2VDIxOjE1OjU5LjM3OSswNzowMCIsInVwZGF0ZWRfYXQiOiIyMDI1LTA1LTI2VDIxOjE1OjU5LjM3OSswNzowMCJ9XSwidXNlcl9pZCI6MX0.wPjlN5xw_f6uYvACDVg2RsyriqPTBAcxDlX26mnWQ0Y
Content-Type: application/json

{
  "title": "Jangjawokan",
  "body": "Isi lengkap artikel"
}

###
DELETE http://localhost:8080/api/dashboard/post/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ4MzYyMzcyLCJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJhZG1pbiIsImNyZWF0ZWRfYXQiOiIyMDI1LTA1LTI2VDIxOjE1OjU5LjM3OSswNzowMCIsInVwZGF0ZWRfYXQiOiIyMDI1LTA1LTI2VDIxOjE1OjU5LjM3OSswNzowMCJ9XSwidXNlcl9pZCI6MX0.wPjlN5xw_f6uYvACDVg2RsyriqPTBAcxDlX26mnWQ0Y